run_profile:
  name: lab_poc
  environment: lab
  require_signed_scope: false
  require_allowlist: true
  stop_on_scope_mismatch: true
  stop_on_window_expiry: false

greenbone:
  credential_id: 2da448c5-2b61-4b59-9660-3cc5a0ad41f5

nikto:
  executable: /home/brahim/tools/nikto/program/nikto.pl
  interpreter: perl
  timeout_per_host: 300
  global_timeout: 3600

lynis:
  mode: local
  executable: lynis
  global_timeout: 1800

phases:
  - name: inventory
    enabled: true
    runners: [inventory, osquery]

  - name: service_validation
    enabled: false
    runners: [nmap]

  - name: authenticated_vuln
    enabled: false
    runners: [greenbone]

  - name: config_audit
    enabled: true
    runners: [lynis]

  - name: web_checks
    enabled: false 
    allowed_environments: [staging, lab]
    runners: [zap, nikto, nuclei] #zap, nikto, 

  - name: cloud_posture
    enabled: false
    runners: [prowler, scoutsuite]

workflow:
  import_defectdojo: true
  index_opensearch: false
  create_tickets: false
  deduplicate: true
  